# Generated by Django 5.2 on 2025-05-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Характер цілі')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('time_create', models.TimeField(auto_now_add=True, verbose_name='Час створення запису')),
            ],
            options={
                'verbose_name': 'Характер цілі',
                'verbose_name_plural': 'Характери цілей',
            },
        ),
        migrations.CreateModel(
            name='Howitzers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Модель гармати')),
                ('caliber', models.CharField(max_length=50, verbose_name='Калібр гармати')),
                ('projectiles', models.JSONField(verbose_name='Типи снарядів')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('time_create', models.TimeField(auto_now_add=True, verbose_name='Час створення запису')),
            ],
            options={
                'verbose_name': 'Гармата',
                'verbose_name_plural': 'Гармати',
            },
        ),
        migrations.CreateModel(
            name='ListHeadTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.JSONField(verbose_name='Список колонок в таблиці')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Дата оновлення запису')),
                ('time_update', models.TimeField(auto_now=True, verbose_name='Час оновлення запису')),
            ],
        ),
        migrations.CreateModel(
            name='ResultShooting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Результат стрільби')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('time_create', models.TimeField(auto_now_add=True, verbose_name='Час створення запису')),
            ],
            options={
                'verbose_name': 'Результат стрільби',
                'verbose_name_plural': 'Результати стрільб',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва цілі')),
                ('square', models.CharField(max_length=6, verbose_name='Квадрат')),
                ('coordinate_x', models.CharField(max_length=10, verbose_name='Координата X')),
                ('coordinate_y', models.CharField(max_length=10, verbose_name='Координата Y')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('time_create', models.TimeField(auto_now_add=True, verbose_name='Час створення запису')),
            ],
            options={
                'verbose_name': 'Ціль',
                'verbose_name_plural': 'Цілі',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вогнева позиція')),
                ('remainder', models.SmallIntegerField(verbose_name='Залишок снарядів')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('time_create', models.TimeField(auto_now_add=True, verbose_name='Час створення запису')),
                ('to_howitzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_howitzer', to='hw.howitzers', verbose_name='')),
            ],
            options={
                'verbose_name': 'Вогнева позиція',
                'verbose_name_plural': 'Вогневі позиції',
            },
        ),
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField(verbose_name='Дата початку')),
                ('time_begin', models.TimeField(verbose_name='Час початку')),
                ('time_end', models.TimeField(verbose_name='Час завершення')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('time_create', models.TimeField(auto_now_add=True, verbose_name='Час створення запису')),
                ('to_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoot_character', to='hw.charactertarget', verbose_name='Характер цілі')),
                ('to_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoot_position', to='hw.position', verbose_name='Вогнева позиція')),
                ('to_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoot_result', to='hw.resultshooting', verbose_name='')),
                ('to_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoot_target', to='hw.target', verbose_name='Ціль')),
            ],
            options={
                'verbose_name': 'Стрільба',
                'verbose_name_plural': 'Стрільби',
            },
        ),
    ]
