# Generated by Django 5.2 on 2025-05-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listheadtable',
            options={'verbose_name': 'Колонки', 'verbose_name_plural': 'Колонки'},
        ),
        migrations.AddField(
            model_name='listheadtable',
            name='name',
            field=models.CharField(default='test', max_length=10, verbose_name='Назва'),
        ),
    ]
